title: Nat's Awesome Site
author: Nat
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 In this site, I am learning and practicing how to configure github pages.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
